services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - dbvolume:/var/lib/postgresql/data

  neurocig_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    networks:
      - default
      - network1
    volumes:
      - ${NEUROCIG_ANNOTATIONS_PATH}:${NEUROCIG_ANNOTATIONS_PATH}

networks:
  default:
  network1:
    name: ${NETWORK_NAME}
    external: true

volumes:
  dbvolume:
